### ISSUE TITLE
"Exception: JNI: Init'd AndroidJavaClass with null ptr!" error when running in Unity Editor

### ISSUE THREAD

**Issue by mode80** [adjust/unity_sdk#31] opened 2014-12-12 21:24 UTC
When running the provided "ExampleGUI" scene in the Unity editor*, then clicking the "manual launch" button to initialize Adjust, it fails with a unity console error reading: 

> Exception: JNI: Init'd AndroidJavaClass with null ptr!
> UnityEngine.AndroidJavaClass..ctor (IntPtr jclass)
> UnityEngine.AndroidJavaObject.get_JavaLangClass ()
> UnityEngine.AndroidJavaObject.FindClass (System.String name)
> UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className)
> UnityEngine.AndroidJavaClass..ctor (System.String className)
> com.adjust.sdk.AdjustAndroid..ctor () (at Assets/Plugins/Android/AdjustAndroid.cs:15)
> Adjust.appDidLaunch (System.String appToken, AdjustEnvironment environment, LogLevel logLevel,  Boolean eventBuffering) (at Assets/Adjust.cs:43)
> ExampleGUI.OnGUI () (at Assets/ExampleGUI/ExampleGUI.cs:14)

I think this is because Adjust can only run on the actual platform devices, and therefore shouldn't try to initialize when run from the editor. 

*(osx v4.6)

**Comment by nonelse** [comment] 2015-01-08 14:22
Fixed in new version [v3.4.4](https://github.com/adjust/unity_sdk/releases/tag/v3.4.4)

**Closed by nonelse** 2015-01-08 14:22 UTC

**Comment by wei780901** [comment] 2018-02-07 05:35
I have some issue...
I use sdk version 4.12.1 & unity version 5.6.2 
I don't know to fix it.

**Comment by uerceg** [comment] 2018-02-07 06:43
@wei780901

Can you explain us a bit more about the issue? Is it the same as the one explained in this issue? If yes, can you send us the stack trace? Can you reproduce the issue and if yes, what are the steps?

**Comment by acalandriJC** [comment] 2018-02-07 15:25
Guys, we are having the same problem, here is the stack trace:
Exception: JNI: Init'd AndroidJavaClass with null ptr!
UnityEngine.AndroidJavaClass..ctor (IntPtr jclass) (at /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:562)
UnityEngine.AndroidJavaObject.get_JavaLangClass () (at /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:540)
UnityEngine.AndroidJavaObject.FindClass (System.String name) (at /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:531)
UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) (at /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:551)
UnityEngine.AndroidJavaClass..ctor (System.String className) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/AndroidJavaBindings.gen.cs:92)
com.adjust.sdk.AdjustAndroid..cctor () (at Assets/Adjust/Android/AdjustAndroid.cs:16)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for com.adjust.sdk.AdjustAndroid
com.adjust.sdk.Adjust.OnApplicationPause (Boolean pauseStatus) (at Assets/Adjust/Adjust.cs:59)

**Comment by uerceg** [comment] 2018-02-07 15:28
@acalandriJC 

Can you tell us how do you reproduce this issue? Which Unity version are you using, which Adjust SDK version?

**Comment by acalandriJC** [comment] 2018-02-07 15:32
Sure, we are using unity 5.6.4p2 with adjust sdk 4.12 (we updated from 4.11).
Basically we have the adjust object on scene and when we hit play when tries to initialize it the error occurrs. It does not make the game crash, but its weird since in 4.11 was working just fine and no exceptions were shown.

**Comment by uerceg** [comment] 2018-02-07 15:32
Are you running it in Editor maybe?

**Comment by acalandriJC** [comment] 2018-02-07 15:34
This happens when we click play on the editor, yes, but this wasnt happening in 4.11

**Comment by uerceg** [comment] 2018-02-07 15:48
Ah, interesting, okay. I mean, those methods are not even supposed to be executed in Editor environment for our SDK. I will prepare one demo SDK version soon and post it in here so that you give it a try and let us know if you're still facing the same issue and if not, we'll make official SDK update, if you're willing to give it a try?

**Comment by acalandriJC** [comment] 2018-02-07 17:11
Sure! Thanks!

**Comment by acalandriJC** [comment] 2018-02-07 17:18
Also, dont know why is this happening, but after upgrading adjust, ios low end devices crash when before they wouldnt. Just tried to revert adjust to 4.11 and the game works fine. As soon as i update to 4.12 the same device with the same build with updated adjust crashes on open. The device we are trying it on is an ipad 3. Don't know if could be the same thing or not. Just know that updating to 4.12 is proving to be harder than it should. Thanks for the help though :)

**Comment by uerceg** [comment] 2018-02-08 08:54
@acalandriJC 

Hm. Would it be possible for you to give our upcoming release RC version a try (you can find it in here: https://github.com/adjust/unity_sdk/issues/119#issuecomment-363855199) and let us know if it solved your issue you saw with iPad 3?

**Comment by acalandriJC** [comment] 2018-02-08 13:00
Sure! We will give it a shot and report back with the results, thanks!

**Comment by acalandriJC** [comment] 2018-02-08 14:45
@uerceg Success!!! Whatever you guys did fixed all the issues, the editor errors and the crashes on ios. When can we hope to see a new official release with this fixes?

**Comment by uerceg** [comment] 2018-02-08 14:49
🎉 Official 4.12.2 is being prepared and should be live soon. I hope tomorrow at latest point. Will update in here once live.

**Comment by wei780901** [comment] 2018-02-09 07:36
Sorry late to reply,I use Unity Editor Mode with Andriod platfrom and Clikc play,
The error is showing,
I think this code have problem   
AdjustAndroid.cs line:16
"private static AndroidJavaClass ajcAdjust = new AndroidJavaClass("com.adjust.sdk.Adjust");"

but I correct run in android device.

**Comment by uerceg** [comment] 2018-02-09 07:57
@wei780901 

Thanks for the report. Unity SDK v4.12.2 should be live today and hopefully solve this issue.
