### ISSUE TITLE
Error when building with Xcode 8.2.1

### ISSUE THREAD

**Issue by rthery** [adjust/unity_sdk#110] opened 2017-10-11 07:20 UTC
I was asked to integrate your SDK in a game made with Unity 5.5.4p5, but once the SDK integrated, the iOS build fail with the following error in Xcode (no problem building it for Android though):
`Invalid bitcode version (Producer: '802.0.42.0_0' Reader: '800.0.42.1_0')`

Is there no way around it ? The only solution I could find so far is to upgrade Xcode, which I cannot as my iMac only supports macOS 10.11 maximum.

**Comment by uerceg** [comment] 2017-10-12 07:00
Hi @rthery 

Thanks for reporting this. Which SDK version are you using?

**Comment by rthery** [comment] 2017-10-12 11:46
@uerceg Ah yes sorry, should have mentioned it!
I'm using Adjust_v4.11.4_Unity_5

**Comment by uerceg** [comment] 2017-10-12 11:48
@rthery Thanks! And what's your exact Xcode version?

**Comment by rthery** [comment] 2017-10-12 12:51
Xcode 8.2.1 (it was in the title ;)

**Comment by uerceg** [comment] 2017-10-13 05:39
Right. 😄 Sorry about that.

Anyway, I have downloaded `Unity 5.5.4p5`, made an example app with it and added our `Adjust_v4.11.4_Unity_5` SDK version from releases page, built iOS Xcode project and opened it with `Xcode 8.2.1` and it compiled and ran successfully. 🤔 

Are you sure you maybe didn't just use `AdjustSdk.framework` from iOS SDK releases page and replaced your iOS SDK framework binary inside `Assets` folder of your app? Because when we initially released iOS SDK v4.11.5 (which Unity 4.11.4 uses underneath), we have built it with Xcode 9 which caused some issues for later Xcode versions, but then we have rebuilt it with Xcode 8 and have updated releases page.

With release of Unity SDK v4.11.4 we made sure that it builds with Xcode 7, 8 and 9. I have just tried to build my example app I have made with `5.5.4p5` with Xcode 7.3.1, 8.2.1, 8.3.2 and 9.0 and app was successfully build with no errors in each one of those Xcode versions.

**Comment by rthery** [comment] 2017-10-13 08:42
Tried it on an empty project and didn't encounter that error either.

But in our game, when I remove Adjust from the project, then I can compile it fine. If I put it back, then I encounter that error. 
I just noticed that the error is listed under the file UnityPurcharshing.m (we use Unity IAP service, current version 1.14.0), so I'm guessing there's some incompatibility between the two SDKs, although I admit I'm not familiar enough with Objective-C to understand the actual issue.

**Comment by uerceg** [comment] 2017-11-15 22:16
@rthery 

I still didn't manage to reproduce this issue. Did you manage to find solution in the meantime?

**Comment by rthery** [comment] 2017-11-16 08:37
@uerceg Unfortunately not, I ended up using a coworker's iMac, more recent than mine with Xcode 9.0, where the error is not present. 
I'll have to continue to use that version of Xcode anyway to support iOS 11 specific stuff. I won't have much time in the coming days to debug it further, so if you want to to close this issue, it's fine by me, thanks!

**Comment by uerceg** [comment] 2017-11-16 08:38
@rthery Thanks for the update. I will close it, but in case issue pops up again on your side, feel free to reopen it. Cheers!

**Closed by uerceg** 2017-11-16 08:38 UTC
