### ISSUE TITLE
Bitcode issue building with adjust sdk in Xcode 7.2

### ISSUE THREAD

**Issue by andres2000** [adjust/unity_sdk#59] opened 2016-01-09 19:52 UTC
Hi! I'm having an issue trying to Archive an iOS project in Xcode 7.2, using Unity3D 5.3.1p and the adjust unity sdk 4.1.1. I get the following error message:

ld: bitcode bundle could not be generated because '.../Libraries/Adjust/iOS/Adjust.a(Adjust.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The project runs well on device (iPhone 6s) directly from Xcode, I just can't Archive it for distribution. I've gone through the steps in the setup instructions and made sure they are in place (added iAd and AdSupport frameworks; -ObjC linker flag; -fno-objc-arc compile flag on AppStoreDelegate.mm). The AdjustPostBuildiOSLog.txt file is generated correctly and doesn't mention any problem. The 'Enable Bitcode' flag in Xcode Build Settings is set to Yes for both debug and release.

Is Bitcode enabled in the adjust Unity SDK? I'm not familiar with Xcode, so I may be missing something very simple, but I haven't been able to figure it out yet so any pointer is greatly appreciated.  Thanks!

**Comment by uerceg** [comment] 2016-01-12 10:49
Hi @andres2000 

That's weird since our iOS SDK library is build with Bitcode support. I did tests with `Unity 5.3.0f4` and I basically am unable even to build project generated for XCode 7.2 because once I enable Bitcode support, I am getting this error (which is basically unrelated to our SDK):

```
ld: '/Users/uerceg/Projects/Unity/Unity 5/UnityExample/XCodeProject/Libraries/
libiPhone-lib.a(GameCenter.o)' does not contain bitcode. You must rebuild it with 
bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from 
the vendor, or disable bitcode for this target. for architecture armv7
```

I am not sure if Unity fixed this with `5.3.1p` release, but I will give it a try in order to fully reproduce your developing environment. I will try with your Unity version and let you know if I was able to reproduce your issue.

**Comment by uerceg** [comment] 2016-01-20 14:32
@andres2000 

I tested our SDK v4.1.1 with Unity 5.3.1 and XCode 7.2 and I was unable to reproduce issue you reported.

Our iOS native library is build with Bitcode support, that's for sure.

**Comment by ddialer** [comment] 2016-02-02 15:22
Got the same issue.
SDK v4.1.2 with Unity 5.3.2 and XCode 7.2.

Here is full error message:
```
Ld /Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/geapp normal arm64
    cd /Users/Serge/Desktop/GitHub/builds/iOS
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -L/Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -L/Users/Serge/Desktop/GitHub/builds/iOS -L/Users/Serge/Desktop/GitHub/builds/iOS/Libraries -L/Users/Serge/Desktop/GitHub/builds/iOS/Libraries/Adjust/iOS -F/Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -F/Users/Serge/Desktop/GitHub/builds/iOS/Frameworks/FacebookSDK/Plugins/iOS -filelist /Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/geapp.LinkFileList -Xlinker -map -Xlinker /Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/geapp-LinkMap-normal-arm64.txt -miphoneos-version-min=6.0 -dead_strip -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -weak_framework CoreMotion -weak-lSystem -ObjC -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework Storekit -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -weak_framework iAd -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -liPhone-lib -framework FBSDKLoginKit /Users/Serge/Desktop/GitHub/builds/iOS/Libraries/Adjust/iOS/AdjustSdk.a -framework FBSDKShareKit -framework FBSDKCoreKit -framework Bolts -weak_framework AdSupport -Xlinker -dependency_info -Xlinker /Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/geapp_dependency_info.dat -o /Users/Serge/Library/Developer/Xcode/DerivedData/Unity-iPhone-dujezyvaugpwjwdgzbaisrralpcd/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/arm64/geapp

ld: warning: arm64 function not 4-byte aligned: ltmp0 from /Users/Serge/Desktop/GitHub/builds/iOS/Libraries/libiPhone-lib.a(PLCrashAsyncThread_current-5565F35D16E4818B.o)
ld: warning: arm64 function not 4-byte aligned: _plcrash_async_thread_state_current from /Users/Serge/Desktop/GitHub/builds/iOS/Libraries/libiPhone-lib.a(PLCrashAsyncThread_current-5565F35D16E4818B.o)
ld: warning: arm64 function not 4-byte aligned: ltmp0 from /Users/Serge/Desktop/GitHub/builds/iOS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/Serge/Desktop/GitHub/builds/iOS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: bitcode bundle could not be generated because '/Users/Serge/Desktop/GitHub/builds/iOS/Libraries/Adjust/iOS/AdjustSdk.a(Adjust.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any Ideas?

**Comment by andres2000** [comment] 2016-02-02 20:31
Hi, thanks for looking into it. In case it helps, I'm still having the same issue (on Unity 5.3.1p1 Personal and xCode 7.2). I've tried deleting the xCode project and building it again from scratch (rather than 'Appending') and it doesn't make a difference. I've also tried removing the Adjust SDK, and that did solve the issue - everything worked correctly and xCode allowed me to archive and upload to App Store.

**Comment by andres2000** [comment] 2016-02-26 16:12
Hi, after updating to version 4.1.3 of the SDK, xCode 7.2.1, and upgrading Unity to a Pro license (still Unity 5.3.1p1), the problem has disappeared. Not sure which of those changes did the trick, as I didn't do any intermediate attempt. Sounds like the issue is already resolved for me. Thank you!

**Comment by uerceg** [comment] 2016-02-26 16:27
@andres2000 Thank you for the update. Glad it works now for you. I will close this issue and if anyone encounters problems from this issue again, feel free to reopen it. 

Cheers

**Closed by uerceg** 2016-02-26 16:27 UTC
